#!/usr/bin/env bash


while true
do

	echo ""

	if [[ -z "${ENERGI_WALLET_ADDR}" ]] ; then

		echo "No wallet address is set! You may edit this script or enter it below."

		read -p "Enter wallet address: " ENERGI_WALLET_ADDR

		if [ -n "$ENERGI_WALLET_ADDR" ]; then

			break

		fi

	else

		break

	fi

done

# Define unlock command
UNLOCK_CMD="personal.unlockAccount('${ENERGI_WALLET_ADDR}', null, 0, true)"

# Unlock the account (asks user for password)
energi3 attach --exec "${UNLOCK_CMD}"

echo ""

exit
